#!/bin/bash

set -e

usage() {
	echo "usage: $(basename "$0") [-c]" >&2
	exit 1
}

do_clean=
while test $# -gt 0
do
	case $1 in
	-c)
		do_clean=YesPlease
		;;
	*)
		usage
		;;
	esac
	shift
done

. /etc/makepkg.conf

if test -n "$do_clean"
then
	rm -f */*"$PKGEXT"
fi

for i in general miscellaneous specfun struct optim audio control image \
	signal communications linear-algebra mechanics nnet io statistics \
	geometry queueing strings financial fpl msh bim database \
	data-smoothing informationtheory java octcdf octclip octproj \
	physicalconstants plot quaternion sockets splines symbolic nan
do
	pkgname="octave-$i"
	(
		cd "$pkgname"
		. PKGBUILD
		if test x"$arch" != x"any"
		then
			arch="$CARCH"
		fi
		pkg_file="$pkgname-$pkgver-$pkgrel-$arch$PKGEXT"
		if ! test -f "$pkg_file"
		then
			makepkg -s
		fi
		sudo pacman --needed -U "$pkg_file"
	)
done
