#!/bin/sh

set -e

for i in octave-miscellaneous octave-specfun octave-struct octave-optim \
	octave-audio octave-control octave-image octave-signal \
	octave-communications octave-linear-algebra octave-mechanics \
	octave-nnet octave-io octave-statistics octave-geometry \
	octave-queueing octave-strings
do
	(
		cd "$i"
		rm -f *.pkg.tar.xz
		makepkg -f -s -i --noconfirm
	)
done
