#!/bin/sh

usage()
{
	echo "usage: $(basename $0) pack" >&2
}

if test $# -lt 1
then
	usage
	exit 1
fi

_pack=$1
pkgname=octave-$_pack
version=$(sed -n 's/^pkgver=\([0-9.]\+\)/\1/p' $pkgname/PKGBUILD)


git add $pkgname
git commit -m "$_pack $version"
