#!/bin/sh

pkgname=${PWD##*/}

git init
git config core.autocrlf false

cat >> .gitignore << EOF
*.tar.gz
*.tar.xz
pkg/
src/
EOF

mksrcinfo

git add .
git commit -m "Initial commit"
git remote add origin ssh://aur@aur.archlinux.org/${pkgname}.git
git push -u origin master
